"""Recovery uses the current lease's account, fresh controls and existing OTPs."""
from dataclasses import replace
from datetime import datetime, timedelta, timezone
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "windows"))
from apex_automation.account_provider import OtpCode, OtpMethod, SecretCredentials, LeaseProviderError, LeaseStaleError
from apex_automation.ea_app import EaAppAutomationError, EaCaptchaRequired, EaUiState
from apex_automation.ea_app_win32 import EaObservation, WindowsEaHybridDriver
from apex_automation.ea_evidence import EaLoginEvidence
from apex_automation.ea_pages import EaPage, classify_page
from apex_automation.ocr_obstacles import OcrToken


class PasswordRecoveryTest(unittest.TestCase):
    def setUp(self):
        data = json.loads((Path(__file__).parent / "fixtures" / "ea-password-recovery.json").read_text())
        self.frames = {}
        for name, tokens in data["frames"].items():
            tokens = tuple(OcrToken(t["text"], t["confidence"], tuple(t["roi"])) for t in tokens)
            self.frames[name] = EaObservation(tuple(data["rect"]), np.zeros((1, 1), np.uint8),
                                              tokens, classify_page(t.normalized for t in tokens))
        self.credentials = SecretCredentials("fixture@example.test", "FixturePass42!",
                                             (OtpMethod.TOTP, OtpMethod.EMAIL))
        account = self.frames["recovery_account"]
        self.typed_account = replace(account, tokens=account.tokens + (
            OcrToken(self.credentials.login_identifier, .99, (825, 623, 1190, 646)),
        ))

    def flow(self, method=OtpMethod.TOTP):
        # This input page is the established EA code-entry layout, absent
        # from the user's recovery screenshot sequence.
        copy = "Enter the verification code generated by the App Authenticator."
        if method is OtpMethod.EMAIL:
            copy = "We sent a code to fi*****@example.test. Check your spam folder."
        otp = replace(self.frames["otp_method"], page=EaPage.OTP, tokens=(
            OcrToken("Enter your code", .99), OcrToken(copy, .99),
            OcrToken("Enter 6 digit code", .99, (825, 600, 1170, 630)),
            OcrToken("NEXT", .99, (995, 730, 1056, 750)),
        ))
        result = [self.frames["rejected"], self.frames["recovery_account"],
                  self.typed_account, self.frames["otp_method"]]
        if method is OtpMethod.TOTP:
            result.append(self.frames["otp_method"])  # re-observe selection
        return result + [otp, otp, self.frames["reset_password"],
                         self.frames["reset_password_focused"],
                         self.frames["success"], self.frames["login_account"]]

    def driver(self, observations):
        driver = object.__new__(WindowsEaHybridDriver)
        self.clicks, self.typed, self.records, self.otp_methods = [], [], [], []
        self.remaining = list(observations)
        def observe(_hwnd):
            if not self.remaining:
                self.fail("unexpected additional capture")
            return self.remaining.pop(0)
        def wait(_hwnd, _pages, **_kwargs):
            return observe(_hwnd)
        def submit_otp(_hwnd, _observation, supplier, *, method, challenge_started_at):
            self.otp_methods.append(method)
            from apex_automation.ea_app import OtpChallenge
            supplier(OtpChallenge("recovery-challenge", challenge_started_at, method))
        driver._observe = observe
        driver._wait_for_page = wait
        driver._click_point = lambda _hwnd, x, y: self.clicks.append((x, y))
        driver._clear_focused_field = lambda: None
        driver._type_secret = self.typed.append
        driver._record = lambda name, *args, **kwargs: self.records.append(name)
        driver._raise_if_account_banned = lambda *args: None
        driver._submit_otp = submit_otp
        driver._login_identifier_verified = True
        driver.sleep = lambda _: None
        driver.notify = lambda _: None
        driver.evidence = None
        return driver

    def recover(self, driver, credentials=None):
        now = datetime.now(timezone.utc)
        driver._recover_password(1, credentials or self.credentials,
            lambda challenge: OtpCode("123456", challenge.challenge_id, now, now + timedelta(seconds=60)))

    def test_screenshot_pages_are_distinct_from_login(self):
        expected = {"rejected": EaPage.PASSWORD, "recovery_account": EaPage.RECOVERY_ACCOUNT,
                    "otp_method": EaPage.OTP_METHOD, "reset_password": EaPage.RESET_PASSWORD,
                    "reset_password_focused": EaPage.RESET_PASSWORD, "success": EaPage.RESET_SUCCESS,
                    "login_account": EaPage.EMAIL}
        self.assertEqual({k: v.page for k, v in self.frames.items()}, expected)

    def test_actual_rapidocr_output_recognises_pages_and_shifted_submit(self):
        data = json.loads((Path(__file__).parent / "fixtures" / "ea-password-recovery-ocr.json").read_text())
        expected = [EaPage.PASSWORD, EaPage.RECOVERY_ACCOUNT, EaPage.OTP_METHOD,
                    EaPage.RESET_PASSWORD, EaPage.RESET_PASSWORD, EaPage.RESET_SUCCESS, EaPage.EMAIL]
        observations = []
        for index, page in enumerate(expected, 1):
            frame = data[str(index)]
            tokens = tuple(OcrToken(t["text"], t["confidence"], tuple(t["roi"])) for t in frame["tokens"])
            observation = EaObservation(tuple(frame["rect"]), np.zeros((1, 1), np.uint8), tokens,
                                        classify_page(t.normalized for t in tokens))
            self.assertEqual(observation.page, page)
            observations.append(observation)
        driver = self.driver([])
        self.assertEqual(driver._recovery_control(observations[3], ("submit",)), (326, 692))
        self.assertEqual(driver._recovery_control(observations[4], ("submit",)), (327, 890))

    def test_transition_still_showing_email_is_not_a_reset_password_form(self):
        tokens = self.frames["reset_password"].tokens + self.frames["recovery_account"].tokens
        self.assertNotEqual(classify_page(t.normalized for t in tokens), EaPage.RESET_PASSWORD)

    def test_invalid_original_password_is_not_replaced_by_an_invented_password(self):
        driver = self.driver(self.flow())
        with self.assertRaises(EaAppAutomationError):
            self.recover(driver, replace(self.credentials, password="too-short"))
        self.assertEqual(self.typed, [self.credentials.login_identifier])

    def test_new_password_is_saved_before_typing_and_committed_after_success(self):
        driver = self.driver(self.flow())
        candidate = replace(self.credentials, password="NewFixture42ABC!", password_reset_id="reset-1")
        events = []
        def handler(action, credentials):
            events.append((action, list(self.typed)))
            return candidate if action == "PREPARE" else replace(candidate, password_reset_id=None)
        driver.configure_password_recovery(handler)
        self.recover(driver, replace(self.credentials, password="short"))
        self.assertEqual(events[0], ("PREPARE", [self.credentials.login_identifier]))
        self.assertEqual(events[1], ("COMMIT", [self.credentials.login_identifier, candidate.password]))
        self.assertIn("password-recovery-new-password", self.records)

    def test_original_rejected_then_replacement_is_tried_once(self):
        rejected = replace(self.frames["reset_password_focused"], tokens=
            self.frames["reset_password_focused"].tokens + (OcrToken("Choose a different password", .99),))
        frames = self.flow()
        # after old SUBMIT: rejection, re-observe, freshly locate new SUBMIT,
        # success, ordinary login
        frames = frames[:-2]  # remove success/login (success belongs -2)
        frames += [rejected, rejected, self.frames["reset_password_focused"],
                   self.frames["success"], self.frames["login_account"]]
        # initial flow without success/login includes input typed form;
        # _reset_result now sees rejection instead of success.
        driver = self.driver(frames)
        candidate=replace(self.credentials,password="ReplacementPass42!",password_reset_id="reset-2")
        driver.configure_password_recovery(lambda action, _: candidate if action=="PREPARE"
            else replace(candidate,password_reset_id=None))
        self.recover(driver)
        self.assertEqual(self.typed,[self.credentials.login_identifier,self.credentials.password,candidate.password])

    def test_unknown_result_never_generates_another_password(self):
        driver=self.driver(self.flow())
        calls=[]
        driver.configure_password_recovery(lambda *args:calls.append(args))
        driver._reset_result=lambda _: (_ for _ in ()).throw(EaAppAutomationError("unknown result"))
        with self.assertRaises(EaAppAutomationError): self.recover(driver)
        self.assertEqual(calls,[])

    def test_failed_commit_leaves_candidate_and_stops_this_account(self):
        driver=self.driver(self.flow())
        candidate=replace(self.credentials,password="ReplacementPass42!",password_reset_id="reset-3")
        def handler(action,_):
            if action=="PREPARE":return candidate
            raise EaAppAutomationError("writeback unavailable")
        driver.configure_password_recovery(handler)
        with self.assertRaises(EaAppAutomationError):self.recover(driver,replace(self.credentials,password="short"))
        self.assertNotIn("password-recovery-login-ready",self.records)

    def test_original_password_recovery_uses_authenticator_and_moved_submit(self):
        driver = self.driver(self.flow())
        self.recover(driver)
        self.assertEqual(self.typed, [self.credentials.login_identifier, self.credentials.password])
        self.assertEqual(self.otp_methods, [OtpMethod.TOTP])
        self.assertIn((1024, 915), self.clicks)
        self.assertNotIn((1024, 747), self.clicks)
        self.assertEqual(self.records[-2:], ["password-recovery-success", "password-recovery-login-ready"])
        self.assertEqual(self.remaining, [])

    def test_email_only_account_uses_email_code(self):
        driver = self.driver(self.flow(OtpMethod.EMAIL))
        self.recover(driver, replace(self.credentials, otp_methods=(OtpMethod.EMAIL,)))
        self.assertEqual(self.otp_methods, [OtpMethod.EMAIL])
        self.assertNotIn((1025, 699), self.clicks)  # authenticator option
        self.assertEqual(self.records[-1], "password-recovery-login-ready")

    def test_identifier_echo_must_be_this_account_and_confident(self):
        for token in (OcrToken("other@example.test", .99, (825, 623, 1190, 646)),
                      OcrToken(self.credentials.login_identifier, .40, (825, 623, 1190, 646))):
            with self.subTest(token=token):
                flow = self.flow()
                flow[2] = replace(self.frames["recovery_account"], tokens=(token,))
                driver = self.driver(flow)
                with self.assertRaises(EaAppAutomationError):
                    self.recover(driver)
                self.assertEqual(self.typed, [self.credentials.login_identifier])
                self.assertEqual(self.otp_methods, [])

    def test_unverified_previous_login_never_starts_recovery(self):
        driver = self.driver(self.flow())
        driver._login_identifier_verified = False
        with self.assertRaises(EaAppAutomationError):
            self.recover(driver)
        self.assertEqual(self.clicks, [])
        self.assertEqual(self.typed, [])

    def test_missing_or_uncertain_submit_never_uses_stale_position(self):
        for confidence, roi in ((.40, (979, 904, 1070, 927)), (.99, None)):
            with self.subTest(confidence=confidence, roi=roi):
                flow = self.flow()
                focused = self.frames["reset_password_focused"]
                flow[-3] = replace(focused, tokens=tuple(t for t in focused.tokens if t.normalized != "submit") + (
                    OcrToken("SUBMIT", confidence, roi),
                ))
                driver = self.driver(flow)
                with self.assertRaises(EaAppAutomationError):
                    self.recover(driver)
                self.assertNotIn((1024, 747), self.clicks)
                self.assertNotIn((1024, 915), self.clicks)
                self.assertNotIn("password-recovery-success", self.records)

    def test_submit_without_success_does_not_proceed_to_login(self):
        flow = self.flow()
        flow[-2] = self.frames["reset_password_focused"]
        driver = self.driver(flow)
        original = driver._reset_result
        def result(hwnd):
            with patch("apex_automation.ea_password_recovery.time.monotonic", side_effect=[0, 1, 30]):
                return original(hwnd)
        driver._reset_result = result
        with self.assertRaises(EaAppAutomationError):
            self.recover(driver)
        self.assertNotIn("password-recovery-success", self.records)
        self.assertNotIn("password-recovery-login-ready", self.records)

    def test_otp_provider_failure_is_a_bounded_account_failure(self):
        driver=self.driver(self.flow())
        driver._submit_otp=lambda *args,**kwargs: (_ for _ in ()).throw(
            LeaseProviderError("mail unavailable",code="MAIL_UNAVAILABLE"))
        with self.assertRaises(EaAppAutomationError):self.recover(driver)
        self.assertEqual(self.typed,[self.credentials.login_identifier])

    def test_stale_lease_is_never_hidden_as_a_password_failure(self):
        driver=self.driver(self.flow())
        driver._submit_otp=lambda *args,**kwargs: (_ for _ in ()).throw(LeaseStaleError("stale"))
        with self.assertRaises(LeaseStaleError):self.recover(driver)
        self.assertEqual(self.typed,[self.credentials.login_identifier])

    def test_captcha_stops_before_password_entry(self):
        flow = self.flow()
        flow[3] = replace(self.frames["otp_method"], page=EaPage.CAPTCHA)
        driver = self.driver(flow)
        with self.assertRaises(EaCaptchaRequired):
            self.recover(driver)
        self.assertEqual(self.typed, [self.credentials.login_identifier])

    def test_reset_form_cannot_be_used_as_a_login_or_signed_in_identity(self):
        for name in ("recovery_account", "reset_password", "success"):
            with self.subTest(name=name):
                driver = self.driver([])
                observation = self.frames[name]
                driver._identity = lambda _: self.fail("must not read recovery as identity")
                self.assertEqual(driver._state(1, observation), EaUiState.LOGIN)
                driver._ea_window = lambda: 1
                driver._observe = lambda _: observation
                self.assertIsNone(driver.current_identity())

    def test_recovery_evidence_contains_no_account_password_or_code(self):
        driver = self.driver(self.flow())
        with tempfile.TemporaryDirectory() as root:
            driver.evidence = EaLoginEvidence(Path(root), save_screenshots=False)
            driver.evidence.protect(self.credentials.login_identifier, self.credentials.password)
            driver._record = lambda *args, **kwargs: WindowsEaHybridDriver._record(driver, *args, **kwargs)
            self.recover(driver)
            for path in Path(root).rglob("*.jsonl"):
                text = path.read_text()
                for secret in (self.credentials.login_identifier, self.credentials.password, "123456"):
                    self.assertNotIn(secret, text)


if __name__ == "__main__":
    unittest.main()
