from __future__ import annotations

from pathlib import Path
import json
import sys
import tempfile
import unittest


import numpy as np


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY_ROOT / "windows"))

from apex_automation.account_provider import OtpMethod, SecretCredentials
from apex_automation.ea_app import (
    EaApexStartFailed,
    EaLoginRejected,
    EaOtpUnavailable,
)
from apex_automation.ea_app_win32 import EaObservation, WindowsEaHybridDriver
from apex_automation.ea_evidence import (
    EaLoginEvidence,
    SecretHints,
    is_sensitive_text,
)
from apex_automation.ea_pages import (
    AUTHENTICATOR_TERMS,
    EMAIL_CODE_TERMS,
    OTP_FIELD_TERMS,
    PASSWORD_FIELD_TERMS,
    PASSWORD_LINK_TERMS,
    SEND_CODE_TERMS,
    SUBMIT_TERMS,
    EaPage,
    classify_page,
    has_any,
    identity_candidates,
    identity_matches,
    is_login_error,
    is_ui_chrome,
    mask_identity,
    page_markers,
    password_page_blocker,
)
from apex_automation.ocr_obstacles import OcrToken, normalize_ocr_text


def tokens(*texts: str) -> tuple[str, ...]:
    return tuple(normalize_ocr_text(text) for text in texts)


# Real EA surfaces, transcribed as OCR returns them: one text block per line.
EMAIL_PAGE = tokens(
    "Sign in",
    "Email or EA ID",
    "Forgot your password?",
    "Next",
    "Create an account",
)

PASSWORD_PAGE = tokens(
    "Sign in",
    "player@example.test",
    "Password",
    "Forgot your password?",
    "Sign in",
)

# EA raises these on a new device. Transcribed from the real client.
OTP_METHOD_PAGE = tokens(
    "< BACK",
    "Verify your identity",
    "In order to verify your identity, we'll send you a code to your preferred "
    "method below.",
    "Email ma*****@outlook.com",
    "Use my App Authenticator",
    "SEND CODE",
)

OTP_AUTHENTICATOR_PAGE = tokens(
    "< BACK",
    "Enter your code",
    "Enter the verification code generated by the App Authenticator.",
    "CODE",
    "Enter 6 digit code",
    "Remember this device",
    "NEXT",
)

OTP_EMAIL_PAGE = tokens(
    "< BACK",
    "Enter your code",
    "We sent a code to ma*****@outlook.com.",
    "CODE",
    "Enter 6 digit code",
    "Remember this device",
    "NEXT",
    "If you don't see the email in your inbox, check your spam folder and "
    "promotions tab. If you still don't see it, request a resend.",
)

SIGNED_IN_PAGE = tokens(
    "Store",
    "Library",
    "Browse",
    "Search",
    "maraninovo253",
    "Apex Legends",
)


class PageClassificationTest(unittest.TestCase):
    def test_forgot_password_link_does_not_make_the_email_page_a_password_page(
        self,
    ) -> None:
        self.assertIs(classify_page(EMAIL_PAGE), EaPage.EMAIL)

    def test_password_page_is_recognised_while_the_email_is_still_displayed(
        self,
    ) -> None:
        self.assertIs(classify_page(PASSWORD_PAGE), EaPage.PASSWORD)

    def test_account_field_wins_a_transition_frame(self) -> None:
        transition = EMAIL_PAGE + tokens("Password")
        self.assertIs(classify_page(transition), EaPage.EMAIL)
        self.assertEqual(
            password_page_blocker(transition),
            "ACCOUNT_LABEL_STILL_VISIBLE",
        )

    def test_blockers_name_the_two_stalled_states_apart(self) -> None:
        self.assertEqual(password_page_blocker(EMAIL_PAGE), "STILL_ON_ACCOUNT_PAGE")
        self.assertEqual(password_page_blocker(PASSWORD_PAGE), "")
        self.assertEqual(password_page_blocker(tokens("Loading")), "NO_PASSWORD_FIELD")

    def test_otp_and_captcha_outrank_the_login_fields(self) -> None:
        self.assertIs(classify_page(OTP_AUTHENTICATOR_PAGE), EaPage.OTP)
        self.assertIs(
            classify_page(EMAIL_PAGE + tokens("hCaptcha")),
            EaPage.CAPTCHA,
        )

    def test_the_method_chooser_is_not_a_code_page(self) -> None:
        # Typing a code into the chooser goes nowhere: it has no input, only
        # a preselected email option and a Send Code button.
        self.assertIs(classify_page(OTP_METHOD_PAGE), EaPage.OTP_METHOD)
        self.assertIs(classify_page(OTP_EMAIL_PAGE), EaPage.OTP)

    def test_the_email_code_page_is_distinguishable(self) -> None:
        # A generated TOTP can never satisfy it, so it has to be told apart
        # from the authenticator page rather than answered.
        self.assertTrue(has_any("".join(OTP_EMAIL_PAGE), EMAIL_CODE_TERMS))
        self.assertFalse(has_any("".join(OTP_AUTHENTICATOR_PAGE), EMAIL_CODE_TERMS))

    def test_the_authenticator_option_is_findable_on_the_chooser(self) -> None:
        self.assertTrue(has_any("".join(OTP_METHOD_PAGE), AUTHENTICATOR_TERMS))
        self.assertTrue(has_any("".join(OTP_METHOD_PAGE), SEND_CODE_TERMS))

    def test_signed_in_needs_more_than_one_marker(self) -> None:
        self.assertIs(classify_page(SIGNED_IN_PAGE), EaPage.SIGNED_IN)
        self.assertIs(classify_page(tokens("Store")), EaPage.UNKNOWN)

    def test_expired_session_is_its_own_page(self) -> None:
        self.assertIs(
            classify_page(tokens("Your session has expired", "Back to sign in")),
            EaPage.EXPIRED_SESSION,
        )

    def test_login_errors_are_visible_to_the_caller(self) -> None:
        self.assertTrue(
            is_login_error("".join(tokens("Your credentials are incorrect")))
        )
        self.assertFalse(is_login_error("".join(EMAIL_PAGE)))

    def test_markers_describe_a_frame_without_quoting_it(self) -> None:
        markers = page_markers(PASSWORD_PAGE)
        self.assertIn("password", markers)
        self.assertIn("passwordLink", markers)
        self.assertNotIn("account", markers)


class IdentityMatchTest(unittest.TestCase):
    def test_candidates_keep_account_shaped_runs_only(self) -> None:
        found = identity_candidates(tokens("maraninovo253", "Play", "1234567890"))
        self.assertIn("maraninovo253", found)
        self.assertNotIn("play", found)
        self.assertNotIn("1234567890", found)

    def test_known_ocr_confusions_still_match(self) -> None:
        self.assertTrue(identity_matches("ubyh3jlp5fr1", "ubyh3j1p5fr1"))
        self.assertTrue(identity_matches("maraninovo253", "maraninov0253"))
        # Captured on the real EA badge: its condensed lowercase `l` was
        # recognised as `i` at 0.981 confidence in three consecutive frames.
        self.assertTrue(identity_matches("ltntlxv5qk84", "itntlxv5qk84"))

    def test_a_different_account_never_matches(self) -> None:
        self.assertFalse(identity_matches("maraninovo253", "maraninovo254"))
        self.assertFalse(identity_matches("maraninovo253", ""))

    def test_masking_keeps_both_ends_only(self) -> None:
        self.assertEqual(mask_identity("maraninovo253"), "mara...o253")

    def test_window_chrome_is_not_an_account_id(self) -> None:
        # "Friends 0/2" sits in the same corner as the badge and normalizes to
        # nine alphanumerics, which read as an account id for one whole run.
        self.assertTrue(is_ui_chrome("friends02"))
        self.assertTrue(is_ui_chrome("installedgames"))
        self.assertFalse(is_ui_chrome("maraninovo253"))
        self.assertFalse(is_ui_chrome("f4vbjqygvlb"))

    def test_identity_reader_protects_the_observed_id_from_evidence(self) -> None:
        protected = []

        class Evidence:
            def protect(self, *values):
                protected.extend(values)

        class Ocr:
            def read(self, frame, region):
                return (OcrToken("itntlxv5qk84", 0.981),)

        driver = object.__new__(WindowsEaHybridDriver)
        driver.evidence = Evidence()
        driver.ocr = Ocr()
        driver._live = lambda hwnd: hwnd
        driver._frame = lambda: np.zeros((1080, 1920), dtype=np.uint8)
        driver._clip_rect = lambda hwnd, frame: (0, 0, 1920, 1080)

        identity = driver._identity(1)

        self.assertIsNotNone(identity)
        self.assertEqual(protected, ["itntlxv5qk84"])


class AnchorTargetingTest(unittest.TestCase):
    """`_anchor` is a static rule over OCR boxes, so it runs off Windows."""

    WINDOW = (100, 100, 700, 900)

    def observation(self, *placed: tuple[str, int, int, float]) -> EaObservation:
        tokens = tuple(
            OcrToken(text, confidence, (x - 40, y - 8, x + 40, y + 8))
            for text, x, y, confidence in placed
        )
        return EaObservation(
            rect=self.WINDOW,
            frame=np.zeros((1, 1), dtype=np.uint8),
            tokens=tokens,
            page=classify_page(token.normalized for token in tokens),
        )

    def test_password_anchor_never_lands_on_the_reset_link(self) -> None:
        observation = self.observation(
            ("Forgot your password?", 400, 640, 0.99),
            ("Password", 400, 500, 0.80),
        )
        point = WindowsEaHybridDriver._anchor(
            observation,
            PASSWORD_FIELD_TERMS,
            y_range=(0.20, 0.80),
            exclude=PASSWORD_LINK_TERMS,
        )
        self.assertEqual(point, (400, 500))

    def test_submit_anchor_prefers_the_first_named_term(self) -> None:
        observation = self.observation(
            ("Sign in", 400, 300, 0.99),
            ("Next", 400, 650, 0.70),
        )
        point = WindowsEaHybridDriver._anchor(
            observation,
            SUBMIT_TERMS,
            y_range=(0.35, 0.95),
        )
        self.assertEqual(point, (400, 650))

    def test_tokens_outside_the_band_are_ignored(self) -> None:
        observation = self.observation(("Next", 400, 150, 0.99))
        self.assertIsNone(
            WindowsEaHybridDriver._anchor(
                observation,
                SUBMIT_TERMS,
                y_range=(0.35, 0.95),
            )
        )

    def test_otp_field_anchor_does_not_land_on_generic_code_copy(self) -> None:
        observation = self.observation(
            ("Enter your code", 400, 320, 0.99),
            (
                "Enter the verification code generated by the App Authenticator.",
                400,
                370,
                0.99,
            ),
        )
        self.assertIsNone(
            WindowsEaHybridDriver._anchor(
                observation,
                OTP_FIELD_TERMS,
                y_range=(0.20, 0.80),
            )
        )

    def test_otp_field_anchor_keeps_the_real_placeholder(self) -> None:
        observation = self.observation(
            ("Enter your code", 400, 320, 0.99),
            ("Enter 6 digit code", 400, 500, 0.90),
        )
        self.assertEqual(
            WindowsEaHybridDriver._anchor(
                observation,
                OTP_FIELD_TERMS,
                y_range=(0.20, 0.80),
            ),
            (400, 500),
        )

    def test_identifier_echo_survives_ocr_dropping_punctuation(self) -> None:
        observation = self.observation(("player@example.test", 400, 500, 0.90))
        self.assertTrue(
            WindowsEaHybridDriver._identifier_echoed(
                observation,
                "player@example.test",
            )
        )
        self.assertFalse(
            WindowsEaHybridDriver._identifier_echoed(
                self.observation(("Email or EA ID", 400, 500, 0.90)),
                "player@example.test",
            )
        )

    def test_exact_play_anchor_does_not_match_free_to_play_copy(self) -> None:
        observation = self.observation(
            ("Apex Legends is free-to-play. Download it to start playing.", 400, 500, 0.99),
            ("PLAY", 500, 600, 0.90),
        )

        point = WindowsEaHybridDriver._anchor(
            observation,
            ("play", "launch"),
            x_range=(0.35, 0.75),
            y_range=(0.30, 0.70),
            exact=True,
        )

        self.assertEqual(point, (500, 600))

    def test_installed_library_card_derives_its_icon_only_play_control(self) -> None:
        observation = self.observation(
            ("已安装 (1)", 350, 245, 0.99),
            ("Apex Legends", 120, 220, 0.99),
            ("Apex Legends", 335, 608, 0.98),
        )

        point = WindowsEaHybridDriver._installed_library_play_point(observation)

        self.assertEqual(point, (407, 576))


class EaLaunchRecoveryTest(unittest.TestCase):
    WINDOW = (0, 0, 1920, 1080)

    @classmethod
    def observation(cls, *placed: tuple[str, int, int]) -> EaObservation:
        tokens = tuple(
            OcrToken(text, 0.99, (x - 50, y - 10, x + 50, y + 10))
            for text, x, y in placed
        )
        return EaObservation(
            rect=cls.WINDOW,
            frame=np.zeros((1, 1), dtype=np.uint8),
            tokens=tokens,
            page=classify_page(token.normalized for token in tokens),
        )

    @staticmethod
    def driver(
        observations: list[EaObservation],
        clicks: list[tuple[int, int]],
        records: list[str],
    ) -> WindowsEaHybridDriver:
        driver = object.__new__(WindowsEaHybridDriver)
        driver._ea_window = lambda: 1
        driver._observe = lambda _hwnd: observations.pop(0)
        driver._click_point = lambda _hwnd, x, y: clicks.append((x, y))
        driver._record = lambda step, *_args, **_kwargs: records.append(step)
        driver._process_running = lambda _name: False
        driver.sleep = lambda _seconds: None
        return driver

    def test_download_page_fails_fast_without_clicking_playing_copy(self) -> None:
        entry = self.observation(("Apex Legends", 120, 460))
        download = self.observation(
            ("Apex Legends is free-to-play. Download it to start playing.", 900, 500),
            ("DOWNLOAD", 975, 535),
        )
        clicks: list[tuple[int, int]] = []
        records: list[str] = []
        driver = self.driver([entry, download], clicks, records)

        with self.assertRaisesRegex(EaApexStartFailed, "只提供 Download"):
            driver.start_apex()

        self.assertEqual(clicks, [(120, 460)])
        self.assertEqual(records, ["apex-entry", "apex-download-required"])

    def test_installed_library_card_uses_its_icon_only_play_control(self) -> None:
        library = self.observation(
            ("已安装 (1)", 350, 245),
            ("Apex Legends", 120, 460),
            ("Apex Legends", 335, 608),
        )
        clicks: list[tuple[int, int]] = []
        records: list[str] = []
        driver = self.driver([library, library], clicks, records)
        driver._process_running = lambda _name: len(clicks) >= 2

        driver.start_apex()

        self.assertEqual(clicks, [(120, 460), (565, 565)])
        self.assertEqual(records, ["apex-entry", "apex-library-play"])


class LoginSubmitRecoveryTest(unittest.TestCase):
    @staticmethod
    def observation(page_tokens: tuple[str, ...]) -> EaObservation:
        placed = tuple(
            OcrToken(text, 0.99, (100, 100 + index * 30, 500, 125 + index * 30))
            for index, text in enumerate(page_tokens)
        )
        return EaObservation(
            rect=(0, 0, 600, 900),
            frame=np.zeros((1, 1), dtype=np.uint8),
            tokens=placed,
            page=classify_page(token.normalized for token in placed),
        )

    @staticmethod
    def driver(
        email: EaObservation,
        waits: list[EaObservation],
        submissions: list[str],
        records: list[str],
    ) -> WindowsEaHybridDriver:
        driver = object.__new__(WindowsEaHybridDriver)
        driver._click_target = lambda *_args, **_kwargs: "anchor"
        driver._clear_focused_field = lambda: None
        driver._type_secret = lambda _value: None
        driver.sleep = lambda _seconds: None
        driver._observe = lambda _hwnd: email
        driver._submit = lambda *_args, **_kwargs: submissions.pop(0)
        driver._wait_for_page = lambda *_args, **_kwargs: waits.pop(0)
        driver._record = lambda step, *_args, **_kwargs: records.append(step)
        return driver

    def test_echoed_identifier_gets_one_retry_when_next_does_not_advance(self) -> None:
        email = self.observation(
            tokens(
                "Sign in",
                "Email or EA ID",
                "player@example.test",
                "Next",
            )
        )
        password = self.observation(PASSWORD_PAGE)
        submissions = ["anchor", "enter"]
        waits = [email, password]
        records: list[str] = []
        driver = self.driver(email, waits, submissions, records)

        result = driver._submit_login_identifier(
            1,
            email,
            SecretCredentials("player@example.test", "secret"),
        )

        self.assertIs(result.page, EaPage.PASSWORD)
        self.assertEqual(submissions, [])
        self.assertIn("account-submit-retry", records)

    def test_visible_login_error_is_not_retried(self) -> None:
        email = self.observation(
            tokens(
                "Email or EA ID",
                "player@example.test",
                "Next",
                "Your credentials are incorrect",
            )
        )
        submissions = ["anchor"]
        records: list[str] = []
        driver = self.driver(email, [email], submissions, records)

        with self.assertRaises(EaLoginRejected):
            driver._submit_login_identifier(
                1,
                email,
                SecretCredentials("player@example.test", "secret"),
            )

        self.assertEqual(submissions, [])
        self.assertNotIn("account-submit-retry", records)


class OtpMethodSelectionTest(unittest.TestCase):
    @staticmethod
    def observation(*texts: str) -> EaObservation:
        placed = tuple(
            OcrToken(text, 0.99, (100, 100 + index * 30, 500, 125 + index * 30))
            for index, text in enumerate(texts)
        )
        return EaObservation(
            rect=(0, 0, 600, 900),
            frame=np.zeros((1, 1), dtype=np.uint8),
            tokens=placed,
            page=classify_page(token.normalized for token in placed),
        )

    def test_code_page_selects_the_source_it_describes(self) -> None:
        available = (OtpMethod.TOTP, OtpMethod.EMAIL)

        self.assertIs(
            WindowsEaHybridDriver._otp_page_method(
                self.observation(*OTP_AUTHENTICATOR_PAGE),
                available,
                None,
            ),
            OtpMethod.TOTP,
        )
        self.assertIs(
            WindowsEaHybridDriver._otp_page_method(
                self.observation(*OTP_EMAIL_PAGE),
                available,
                None,
            ),
            OtpMethod.EMAIL,
        )

    def test_email_page_is_rejected_when_provider_has_no_mailbox(self) -> None:
        with self.assertRaises(EaOtpUnavailable):
            WindowsEaHybridDriver._otp_page_method(
                self.observation(*OTP_EMAIL_PAGE),
                (OtpMethod.TOTP,),
                None,
            )

    def test_chooser_prefers_totp_and_falls_back_to_email(self) -> None:
        observation = self.observation(*OTP_METHOD_PAGE)

        def run(methods):
            driver = object.__new__(WindowsEaHybridDriver)
            clicks = []
            driver._anchor = lambda _observation, terms, **_kwargs: (
                (300, 300) if terms == AUTHENTICATOR_TERMS else (300, 600)
            )
            driver._click_point = lambda _hwnd, *point: clicks.append(point)
            driver._click = lambda _hwnd, *point: clicks.append(point)
            driver._observe = lambda _hwnd: observation
            driver._record = lambda *_args, **_kwargs: None
            driver._wait_for_page = lambda *_args, **_kwargs: None
            driver.sleep = lambda _seconds: None
            driver.notify = lambda _message: None
            selected, _ = driver._choose_otp_method(1, observation, methods)
            return selected, clicks

        selected, totp_clicks = run((OtpMethod.TOTP, OtpMethod.EMAIL))
        self.assertIs(selected, OtpMethod.TOTP)
        self.assertEqual(len(totp_clicks), 2)

        selected, email_clicks = run((OtpMethod.EMAIL,))
        self.assertIs(selected, OtpMethod.EMAIL)
        self.assertEqual(len(email_clicks), 1)


class SharedInputStructureTest(unittest.TestCase):
    @unittest.skipUnless(
        sys.platform == "win32",
        "Win32 INPUT structures only exist on Windows",
    )
    def test_ea_driver_shares_the_play_sender_input_structure(self) -> None:
        # ctypes.windll.user32 is process-wide: two structurally identical
        # INPUT classes make whichever module constructs last break the other
        # one's SendInput with "expected LP_INPUT instance instead of LP_INPUT".
        from apex_automation import ea_app_win32, input_win32

        self.assertIs(ea_app_win32.INPUT, input_win32.INPUT)


class EvidenceRedactionTest(unittest.TestCase):
    def test_emails_and_codes_are_sensitive(self) -> None:
        self.assertTrue(is_sensitive_text("player@example.test"))
        self.assertTrue(is_sensitive_text("482913"))
        self.assertFalse(is_sensitive_text("Password"))

    def test_hints_catch_the_identifier_even_when_ocr_drops_punctuation(self) -> None:
        hints = SecretHints.for_login("player.one@example.test")
        self.assertTrue(hints.hits("playerone examp1e"[:9]))
        self.assertTrue(hints.hits("PLAYER.ONE"))
        self.assertFalse(hints.hits("Sign in"))

    def test_stable_ea_identity_can_be_protected_from_screenshots(self) -> None:
        hints = SecretHints.for_login("itntlxv5qk84")
        self.assertTrue(is_sensitive_text("itntlxv5qk84", hints))

    def test_steps_are_written_and_sensitive_values_are_refused(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            evidence = EaLoginEvidence(Path(directory), save_screenshots=False)
            evidence.step(
                "account-typed",
                page="EMAIL",
                markers=("account", "submit"),
                fieldTarget="anchor",
                identifierEchoed=True,
            )
            record = json.loads(evidence.steps_path.read_text(encoding="utf-8"))
            self.assertEqual(record["step"], "account-typed")
            self.assertEqual(record["page"], "EMAIL")
            self.assertTrue(record["identifierEchoed"])
            with self.assertRaises(ValueError):
                evidence.step("leak", page="EMAIL", note="player@example.test")
            with self.assertRaises(ValueError):
                evidence.step("leak", page="EMAIL", loginIdentifier="masked")

    def test_rotating_starts_a_new_attempt(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            evidence = EaLoginEvidence(Path(directory), save_screenshots=False)
            evidence.step("first", page="EMAIL")
            first = evidence.dir
            second = evidence.rotate()
            evidence.step("second", page="PASSWORD")
            self.assertNotEqual(first, second)
            self.assertEqual(
                json.loads((first / "steps.jsonl").read_text(encoding="utf-8"))["seq"],
                1,
            )
            record = json.loads(evidence.steps_path.read_text(encoding="utf-8"))
            self.assertEqual((record["seq"], record["step"]), (1, "second"))

    def test_pruning_keeps_the_recent_attempts(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for name in ("20260101-000000", "20260102-000000", "20260103-000000"):
                (root / name).mkdir(parents=True)
            evidence = EaLoginEvidence(root, keep_attempts=2, save_screenshots=False)
            evidence.prune()
            remaining = sorted(path.name for path in root.iterdir())
            self.assertIn(evidence.dir.name, remaining)
            self.assertNotIn("20260101-000000", remaining)


if __name__ == "__main__":
    unittest.main()
