from __future__ import annotations

from pathlib import Path
import json
import sys
import tempfile
import unittest


import numpy as np


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY_ROOT / "windows"))

from apex_automation.account_provider import OtpMethod
from apex_automation.ea_app import EaOtpUnavailable
from apex_automation.ea_app_win32 import EaObservation, WindowsEaHybridDriver
from apex_automation.ea_evidence import (
    EaLoginEvidence,
    SecretHints,
    is_sensitive_text,
)
from apex_automation.ea_pages import (
    AUTHENTICATOR_TERMS,
    EMAIL_CODE_TERMS,
    PASSWORD_FIELD_TERMS,
    PASSWORD_LINK_TERMS,
    SEND_CODE_TERMS,
    SUBMIT_TERMS,
    EaPage,
    classify_page,
    has_any,
    identity_candidates,
    identity_matches,
    is_login_error,
    is_ui_chrome,
    mask_identity,
    page_markers,
    password_page_blocker,
)
from apex_automation.ocr_obstacles import OcrToken, normalize_ocr_text


def tokens(*texts: str) -> tuple[str, ...]:
    return tuple(normalize_ocr_text(text) for text in texts)


# Real EA surfaces, transcribed as OCR returns them: one text block per line.
EMAIL_PAGE = tokens(
    "Sign in",
    "Email or EA ID",
    "Forgot your password?",
    "Next",
    "Create an account",
)

PASSWORD_PAGE = tokens(
    "Sign in",
    "player@example.test",
    "Password",
    "Forgot your password?",
    "Sign in",
)

# EA raises these on a new device. Transcribed from the real client.
OTP_METHOD_PAGE = tokens(
    "< BACK",
    "Verify your identity",
    "In order to verify your identity, we'll send you a code to your preferred "
    "method below.",
    "Email ma*****@outlook.com",
    "Use my App Authenticator",
    "SEND CODE",
)

OTP_AUTHENTICATOR_PAGE = tokens(
    "< BACK",
    "Enter your code",
    "Enter the verification code generated by the App Authenticator.",
    "CODE",
    "Enter 6 digit code",
    "Remember this device",
    "NEXT",
)

OTP_EMAIL_PAGE = tokens(
    "< BACK",
    "Enter your code",
    "We sent a code to ma*****@outlook.com.",
    "CODE",
    "Enter 6 digit code",
    "Remember this device",
    "NEXT",
    "If you don't see the email in your inbox, check your spam folder and "
    "promotions tab. If you still don't see it, request a resend.",
)

SIGNED_IN_PAGE = tokens(
    "Store",
    "Library",
    "Browse",
    "Search",
    "maraninovo253",
    "Apex Legends",
)


class PageClassificationTest(unittest.TestCase):
    def test_forgot_password_link_does_not_make_the_email_page_a_password_page(
        self,
    ) -> None:
        self.assertIs(classify_page(EMAIL_PAGE), EaPage.EMAIL)

    def test_password_page_is_recognised_while_the_email_is_still_displayed(
        self,
    ) -> None:
        self.assertIs(classify_page(PASSWORD_PAGE), EaPage.PASSWORD)

    def test_account_field_wins_a_transition_frame(self) -> None:
        transition = EMAIL_PAGE + tokens("Password")
        self.assertIs(classify_page(transition), EaPage.EMAIL)
        self.assertEqual(
            password_page_blocker(transition),
            "ACCOUNT_LABEL_STILL_VISIBLE",
        )

    def test_blockers_name_the_two_stalled_states_apart(self) -> None:
        self.assertEqual(password_page_blocker(EMAIL_PAGE), "STILL_ON_ACCOUNT_PAGE")
        self.assertEqual(password_page_blocker(PASSWORD_PAGE), "")
        self.assertEqual(password_page_blocker(tokens("Loading")), "NO_PASSWORD_FIELD")

    def test_otp_and_captcha_outrank_the_login_fields(self) -> None:
        self.assertIs(classify_page(OTP_AUTHENTICATOR_PAGE), EaPage.OTP)
        self.assertIs(
            classify_page(EMAIL_PAGE + tokens("hCaptcha")),
            EaPage.CAPTCHA,
        )

    def test_the_method_chooser_is_not_a_code_page(self) -> None:
        # Typing a code into the chooser goes nowhere: it has no input, only
        # a preselected email option and a Send Code button.
        self.assertIs(classify_page(OTP_METHOD_PAGE), EaPage.OTP_METHOD)
        self.assertIs(classify_page(OTP_EMAIL_PAGE), EaPage.OTP)

    def test_the_email_code_page_is_distinguishable(self) -> None:
        # A generated TOTP can never satisfy it, so it has to be told apart
        # from the authenticator page rather than answered.
        self.assertTrue(has_any("".join(OTP_EMAIL_PAGE), EMAIL_CODE_TERMS))
        self.assertFalse(has_any("".join(OTP_AUTHENTICATOR_PAGE), EMAIL_CODE_TERMS))

    def test_the_authenticator_option_is_findable_on_the_chooser(self) -> None:
        self.assertTrue(has_any("".join(OTP_METHOD_PAGE), AUTHENTICATOR_TERMS))
        self.assertTrue(has_any("".join(OTP_METHOD_PAGE), SEND_CODE_TERMS))

    def test_signed_in_needs_more_than_one_marker(self) -> None:
        self.assertIs(classify_page(SIGNED_IN_PAGE), EaPage.SIGNED_IN)
        self.assertIs(classify_page(tokens("Store")), EaPage.UNKNOWN)

    def test_expired_session_is_its_own_page(self) -> None:
        self.assertIs(
            classify_page(tokens("Your session has expired", "Back to sign in")),
            EaPage.EXPIRED_SESSION,
        )

    def test_login_errors_are_visible_to_the_caller(self) -> None:
        self.assertTrue(
            is_login_error("".join(tokens("Your credentials are incorrect")))
        )
        self.assertFalse(is_login_error("".join(EMAIL_PAGE)))

    def test_markers_describe_a_frame_without_quoting_it(self) -> None:
        markers = page_markers(PASSWORD_PAGE)
        self.assertIn("password", markers)
        self.assertIn("passwordLink", markers)
        self.assertNotIn("account", markers)


class IdentityMatchTest(unittest.TestCase):
    def test_candidates_keep_account_shaped_runs_only(self) -> None:
        found = identity_candidates(tokens("maraninovo253", "Play", "1234567890"))
        self.assertIn("maraninovo253", found)
        self.assertNotIn("play", found)
        self.assertNotIn("1234567890", found)

    def test_known_ocr_confusions_still_match(self) -> None:
        self.assertTrue(identity_matches("ubyh3jlp5fr1", "ubyh3j1p5fr1"))
        self.assertTrue(identity_matches("maraninovo253", "maraninov0253"))

    def test_a_different_account_never_matches(self) -> None:
        self.assertFalse(identity_matches("maraninovo253", "maraninovo254"))
        self.assertFalse(identity_matches("maraninovo253", ""))

    def test_masking_keeps_both_ends_only(self) -> None:
        self.assertEqual(mask_identity("maraninovo253"), "mara...o253")

    def test_window_chrome_is_not_an_account_id(self) -> None:
        # "Friends 0/2" sits in the same corner as the badge and normalizes to
        # nine alphanumerics, which read as an account id for one whole run.
        self.assertTrue(is_ui_chrome("friends02"))
        self.assertTrue(is_ui_chrome("installedgames"))
        self.assertFalse(is_ui_chrome("maraninovo253"))
        self.assertFalse(is_ui_chrome("f4vbjqygvlb"))


class AnchorTargetingTest(unittest.TestCase):
    """`_anchor` is a static rule over OCR boxes, so it runs off Windows."""

    WINDOW = (100, 100, 700, 900)

    def observation(self, *placed: tuple[str, int, int, float]) -> EaObservation:
        tokens = tuple(
            OcrToken(text, confidence, (x - 40, y - 8, x + 40, y + 8))
            for text, x, y, confidence in placed
        )
        return EaObservation(
            rect=self.WINDOW,
            frame=np.zeros((1, 1), dtype=np.uint8),
            tokens=tokens,
            page=classify_page(token.normalized for token in tokens),
        )

    def test_password_anchor_never_lands_on_the_reset_link(self) -> None:
        observation = self.observation(
            ("Forgot your password?", 400, 640, 0.99),
            ("Password", 400, 500, 0.80),
        )
        point = WindowsEaHybridDriver._anchor(
            observation,
            PASSWORD_FIELD_TERMS,
            y_range=(0.20, 0.80),
            exclude=PASSWORD_LINK_TERMS,
        )
        self.assertEqual(point, (400, 500))

    def test_submit_anchor_prefers_the_first_named_term(self) -> None:
        observation = self.observation(
            ("Sign in", 400, 300, 0.99),
            ("Next", 400, 650, 0.70),
        )
        point = WindowsEaHybridDriver._anchor(
            observation,
            SUBMIT_TERMS,
            y_range=(0.35, 0.95),
        )
        self.assertEqual(point, (400, 650))

    def test_tokens_outside_the_band_are_ignored(self) -> None:
        observation = self.observation(("Next", 400, 150, 0.99))
        self.assertIsNone(
            WindowsEaHybridDriver._anchor(
                observation,
                SUBMIT_TERMS,
                y_range=(0.35, 0.95),
            )
        )

    def test_identifier_echo_survives_ocr_dropping_punctuation(self) -> None:
        observation = self.observation(("player@example.test", 400, 500, 0.90))
        self.assertTrue(
            WindowsEaHybridDriver._identifier_echoed(
                observation,
                "player@example.test",
            )
        )
        self.assertFalse(
            WindowsEaHybridDriver._identifier_echoed(
                self.observation(("Email or EA ID", 400, 500, 0.90)),
                "player@example.test",
            )
        )


class OtpMethodSelectionTest(unittest.TestCase):
    @staticmethod
    def observation(*texts: str) -> EaObservation:
        placed = tuple(
            OcrToken(text, 0.99, (100, 100 + index * 30, 500, 125 + index * 30))
            for index, text in enumerate(texts)
        )
        return EaObservation(
            rect=(0, 0, 600, 900),
            frame=np.zeros((1, 1), dtype=np.uint8),
            tokens=placed,
            page=classify_page(token.normalized for token in placed),
        )

    def test_code_page_selects_the_source_it_describes(self) -> None:
        available = (OtpMethod.TOTP, OtpMethod.EMAIL)

        self.assertIs(
            WindowsEaHybridDriver._otp_page_method(
                self.observation(*OTP_AUTHENTICATOR_PAGE),
                available,
                None,
            ),
            OtpMethod.TOTP,
        )
        self.assertIs(
            WindowsEaHybridDriver._otp_page_method(
                self.observation(*OTP_EMAIL_PAGE),
                available,
                None,
            ),
            OtpMethod.EMAIL,
        )

    def test_email_page_is_rejected_when_provider_has_no_mailbox(self) -> None:
        with self.assertRaises(EaOtpUnavailable):
            WindowsEaHybridDriver._otp_page_method(
                self.observation(*OTP_EMAIL_PAGE),
                (OtpMethod.TOTP,),
                None,
            )

    def test_chooser_prefers_totp_and_falls_back_to_email(self) -> None:
        observation = self.observation(*OTP_METHOD_PAGE)

        def run(methods):
            driver = object.__new__(WindowsEaHybridDriver)
            clicks = []
            driver._anchor = lambda _observation, terms, **_kwargs: (
                (300, 300) if terms == AUTHENTICATOR_TERMS else (300, 600)
            )
            driver._click_point = lambda _hwnd, *point: clicks.append(point)
            driver._click = lambda _hwnd, *point: clicks.append(point)
            driver._observe = lambda _hwnd: observation
            driver._record = lambda *_args, **_kwargs: None
            driver._wait_for_page = lambda *_args, **_kwargs: None
            driver.sleep = lambda _seconds: None
            driver.notify = lambda _message: None
            selected, _ = driver._choose_otp_method(1, observation, methods)
            return selected, clicks

        selected, totp_clicks = run((OtpMethod.TOTP, OtpMethod.EMAIL))
        self.assertIs(selected, OtpMethod.TOTP)
        self.assertEqual(len(totp_clicks), 2)

        selected, email_clicks = run((OtpMethod.EMAIL,))
        self.assertIs(selected, OtpMethod.EMAIL)
        self.assertEqual(len(email_clicks), 1)


class SharedInputStructureTest(unittest.TestCase):
    @unittest.skipUnless(
        sys.platform == "win32",
        "Win32 INPUT structures only exist on Windows",
    )
    def test_ea_driver_shares_the_play_sender_input_structure(self) -> None:
        # ctypes.windll.user32 is process-wide: two structurally identical
        # INPUT classes make whichever module constructs last break the other
        # one's SendInput with "expected LP_INPUT instance instead of LP_INPUT".
        from apex_automation import ea_app_win32, input_win32

        self.assertIs(ea_app_win32.INPUT, input_win32.INPUT)


class EvidenceRedactionTest(unittest.TestCase):
    def test_emails_and_codes_are_sensitive(self) -> None:
        self.assertTrue(is_sensitive_text("player@example.test"))
        self.assertTrue(is_sensitive_text("482913"))
        self.assertFalse(is_sensitive_text("Password"))

    def test_hints_catch_the_identifier_even_when_ocr_drops_punctuation(self) -> None:
        hints = SecretHints.for_login("player.one@example.test")
        self.assertTrue(hints.hits("playerone examp1e"[:9]))
        self.assertTrue(hints.hits("PLAYER.ONE"))
        self.assertFalse(hints.hits("Sign in"))

    def test_steps_are_written_and_sensitive_values_are_refused(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            evidence = EaLoginEvidence(Path(directory), save_screenshots=False)
            evidence.step(
                "account-typed",
                page="EMAIL",
                markers=("account", "submit"),
                fieldTarget="anchor",
                identifierEchoed=True,
            )
            record = json.loads(evidence.steps_path.read_text(encoding="utf-8"))
            self.assertEqual(record["step"], "account-typed")
            self.assertEqual(record["page"], "EMAIL")
            self.assertTrue(record["identifierEchoed"])
            with self.assertRaises(ValueError):
                evidence.step("leak", page="EMAIL", note="player@example.test")
            with self.assertRaises(ValueError):
                evidence.step("leak", page="EMAIL", loginIdentifier="masked")

    def test_rotating_starts_a_new_attempt(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            evidence = EaLoginEvidence(Path(directory), save_screenshots=False)
            evidence.step("first", page="EMAIL")
            first = evidence.dir
            second = evidence.rotate()
            evidence.step("second", page="PASSWORD")
            self.assertNotEqual(first, second)
            self.assertEqual(
                json.loads((first / "steps.jsonl").read_text(encoding="utf-8"))["seq"],
                1,
            )
            record = json.loads(evidence.steps_path.read_text(encoding="utf-8"))
            self.assertEqual((record["seq"], record["step"]), (1, "second"))

    def test_pruning_keeps_the_recent_attempts(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for name in ("20260101-000000", "20260102-000000", "20260103-000000"):
                (root / name).mkdir(parents=True)
            evidence = EaLoginEvidence(root, keep_attempts=2, save_screenshots=False)
            evidence.prune()
            remaining = sorted(path.name for path in root.iterdir())
            self.assertIn(evidence.dir.name, remaining)
            self.assertNotIn("20260101-000000", remaining)


if __name__ == "__main__":
    unittest.main()
